### ISSUE TITLE
Setup Webpack For Vue/Vuex

### ISSUE THREAD

**Issue by jonwinton** [nymag/clay-space-edit#52]
Get the build working with anything Vue related. Details to be described once they've been discovered.

**Comment by mheiber** [comment]
For hooking into Kiln's Vuex store, we don't need a change to the build, so the question is:

## Will we use Vue in the UI?

### Pros of using Vue in the 

- We're using Vue for behaviors, consistency is good
- Easier to keep the DOM and the data in sync, probably more maintainable
- Fewer `data-` attributes in the DOM

### Cons of using Vue in the UI
- High development effort. I think doing the UI in Vue would require changes to Kiln. Since the editing UI is removed from the DOM when not active, the only way to get Vue in now, AFAIK, is to re-mount on edit, which sounds bad. Ideally, our UI would show based on something Vue-friendly in Kiln like a `v-if`,  `slot`, child component, prop, 
- Lock-in: Vue won't be cool forever, but the DOM is sticking around for a while.
- Can't reuse existing clay-space-edit UI code.

**Comment by jonwinton** [comment]
Work with the NYMag custom behavior `mediaplay-picker` has given us a good avenue for how to use a Vue component in Kiln, so we should do that as well. We'll need to setup the build to compile a Vue component.

**Comment by mheiber** [comment]
behavior <> plugin, though, right?
Also, some of the considerations above still apply, I think. It would be nice to reuse as much of the existing code for clay-space-edit as possible, which should be just a few tweaks to swap out event-listening for action-subscription.
